### ISSUE TITLE
meetup está com data errada no site 

### ISSUE THREAD

**Issue by fabiohcnobre** [github/brasil#28]
Github Meetup está mostrando evento com data que já passou.  
Por gentileza ajusta pra só mostrar eventos futuros. 
![IMG_8534](https://github.com/github/brasil/assets/22354660/46988369-29a2-4ae1-baa4-753a0963f400)

**Comment by AndreaGriffiths11** [comment]
👍🏽 TYSM for the heads up

**Comment by fabiohcnobre** [comment]
Agora não mostra nada !!!
