### ISSUE TITLE
Site está fora do ar

### ISSUE THREAD

**Issue by mateusarcedev** [github/brasil#33]
![image](https://github.com/github/brasil/assets/96782284/154c3350-d572-4874-952d-949b46e93c1e)

Tentei acessar o site agora e está assim.

**Comment by felipsbreno** [comment]
Olá @mateusarcedev

Parece que o site voltou a funcionar corretamente

![image](https://github.com/github/brasil/assets/50807243/f2faa090-df69-44f6-86dc-7e4bffd2d031)

**Comment by fabiohcnobre** [comment]
Porque não libera o codigo do site para ajustar ?!

**Comment by AndreaGriffiths11** [comment]
Apologies, we had an issue with the certificate, should be resolved now.

**Comment by fabiohcnobre** [comment]
The website is now live again.
But there is no way to release the code to create PR or ISUE?
