### ISSUE TITLE
Cannot access the link in the description

### ISSUE THREAD

**Issue by kevenleone** [github/brasil#4]
Hi all 👋🏻 

It looks really good the idea of this repository, thank you so much for thinking in Brazilian Developers ❤️ 

I tried to open: [githubbrasil.com](https://githubbrasil.com/) and the following message appeared

<img width="1920" alt="image" src="https://github.com/github/brasil/assets/22279592/34ecc386-a001-42a1-b41c-1e5450289287">

This message is expected?

**Comment by AndreaGriffiths11** [comment]
Hiya @kevenleone thank you so much for being here! We'll set the page to public in a few hours, apologies for the delay, excited to get everything nice and tidy!

**Comment by AndreaGriffiths11** [comment]
está vivo! https://githubbrasil.com/
